version: '2'

services:

  php:
    build: .
    volumes: ['./:/app']

  composer:
    extends: { service: php }
    entrypoint: ['composer']

  phpunit:
    extends: { service: php }
    entrypoint: ['./vendor/bin/phpunit']
    env_file: ['.env']

  dist:
    extends: { service: php }
    entrypoint: ['dist.sh']
    env_file: ['.env']

volumes:
  mysql:

